version: "2"

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals
    - goconst
    - gomodguard
    - tagliatelle
    - testpackage
    - wsl
  settings:
    gosec:
      excludes:
        - G204
  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - funlen

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
